version: '3'
services:
  database:
    image: microsoft/mssql-server-linux
    environment:
        SA_PASSWORD: "Root1234567890"
        ACCEPT_EULA: "Y"
    ports:
      - "14330:1433"
  backend:
    build:
      context: backend
      args:
        UID: ${UID:-1001}
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      - database
  frontend:
    build:
      context: frontend
      args:
        UID: ${UID:-1001}
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "4200:4200"